import { ArrowUpRight, MapPin, Menu, X } from "lucide-react";
import { useEffect, useState } from "react";
import ImageViewer, { ShareButtons } from "../components/ImageViewer";
import { SHOW_FAQ } from "../config";

const storageImage = "/assets/council-map.png";
const schools = [
  { name:"サドベリースクールつくば空", yomi:"さどべりーすくーるつくばそら", area:"つくば市春日", tone:"mint", comment:"個性を尊重し、共に育ちあう場。自ら実行することを大事にしています。やりたいことに没頭できる安心の空間です。", target:"小学生・中学生・高校生", site:"https://www.tsukuba-sora.com/" },
  { name:"TSUKUBA学びの杜学園", yomi:"つくばまなびのもりがくえん", area:"つくば市吾妻", tone:"lime", comment:"子どもたちが自分のペースで安心して過ごせる学びの場。週5開校、送迎あり。ご相談は土日も受け付けています。", target:"小学生・中学生・高校生", site:"https://manabinomori-gakuen.com/" },
  { name:"つくばフリースクールKimiiro", yomi:"つくばふりーすくーるきみいろ", area:"つくば市上ノ室", tone:"violet", comment:"「保護者満足度100%」古民家で、週4日開校しています。市外問わず通いやすいプランの用意あり。", target:"小学生・中学生・高校生", site:"https://freeschool-kimiiro.com/" },
  { name:"子ども社会塾", yomi:"こどもしゃかいじゅく", area:"つくば市竹園ほか・オンライン", tone:"gold", comment:"できる子より、“生き残れる子”へ。社会を生き抜く力を早くから習得するためのスクール。学校で教えないこと、教えます。", target:"小学生・中学生・高校生", site:"https://www.sjuku.jp/" },
  { name:"こどもとつくる学校でんでん", yomi:"こどもとつくるがっこうでんでん", area:"つくば市竹園", tone:"cyan", comment:"イエナプランを軸に、子どもの“やりたい”からはじまる生きた本物の学びを実践します。", target:"小学生・中学生（高校生は応相談）", site:"https://denden-alternativeschool.jimdofree.com/" },
  { name:"fermi cafe", yomi:"ふぇるみかふぇ", area:"つくば市二の宮", tone:"purple", comment:"「話す・学ぶ・つながる」好きなことや気持ちに寄り添うサイエンスカフェ。実験講座やAI教室などのイベントも多数。", target:"子どもから大人まで", site:"https://sites.google.com/view/fermi-cafe/" },
  { name:"つくば高等学院", yomi:"つくばこうとうがくいん", area:"つくば市二の宮", tone:"orange", comment:"自分のペースを大切にしながら、ITにも触れられます。ほっと過ごせるフリースクール・通信制高校サポート校。", target:"小学5年〜高校生", site:"https://tsukugaku.com/" },
  { name:"ROBE学園", yomi:"ろーべがくえん", area:"つくば市緑が丘", tone:"brown", comment:"無学年教材で自分のペースで学べる、週3日開所のフリースクール。子ども食堂も利用可能です。", target:"小学生・中学生・高校生", site:"https://npo-robe.org/" },
  { name:"CoreDa!探究ラボ", yomi:"こあだたんきゅうらぼ", area:"つくば市春日", tone:"sky", comment:"子どもたちに豊かな体験を提供し、世の中の面白さと学びの楽しさを伝える習い事教室。2026年10月、新拠点オープンしました！", target:"小学生・中学生・高校生", site:"https://school.oneangle.jp/" },
  { name:"親子の居場所×フリースクール imakoko", yomi:"おやこのいばしょ", area:"つくばみらい市板橋", tone:"pink", comment:"不登校当事者の親子が運営しています。一人ひとりのペースで過ごせる、みんなの心が豊かになれる居場所を目指しています。", target:"小学生・中学生の親子", site:"#", insta:"https://www.instagram.com/imakoko_tsukubamirai/" },
];

function Header(){const [open,setOpen]=useState(false); return <header className="site-header"><a href="/" className="brand"><img className="brand-logo" src="/assets/council-logo.png" alt="つくばフリースクール等連携協議会"/><span><b>つくばフリースクール等連携協議会</b><small>TSUKUBA FREE SCHOOL NETWORK</small></span></a><button className="mobile-toggle" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?"open":""}><a href="#schools" onClick={()=>setOpen(false)}>参加スクール</a><a href="/lecturers">出張講師</a>{SHOW_FAQ && <a href="/faq">よくある質問</a>}<a href="/parents">保護者の方へ</a><a href="/about">協議会とは</a><div className="nav-cta-mobile"><a className="header-cta" href="/donation">寄附をする</a><a className="header-cta header-cta-outline" href="/join">会員登録</a></div></nav><div className="header-actions"><a className="header-cta" href="/donation">寄附をする</a><a className="header-cta header-cta-outline" href="/join">会員登録</a></div></header>}
function Footer(){return <footer><div className="footer-inner"><div><div className="brand footer-brand"><img className="brand-logo" src="/assets/council-logo-footer.png" alt="つくばフリースクール等連携協議会"/><span><b>つくばフリースクール等連携協議会</b><small>TSUKUBA FREE SCHOOL NETWORK</small></span></div><p>子ども一人ひとりが、自分に合った<br/>学びの場とつながれる地域へ。</p></div><div className="footer-links"><div className="footer-col"><b>事務局</b><span>M&amp;Sプロジェクト(担当：西脇)</span><a href="mailto:msproject.tsukuba@gmail.com">msproject.tsukuba@gmail.com</a></div><div className="footer-col"><b>資料</b><a href="/documents/pamphlet.pdf" target="_blank" rel="noreferrer">三つ折りパンフレット(PDF)</a><a href="/documents/overview.pdf" target="_blank" rel="noreferrer">協議会概要スライド(PDF)</a><a href="/documents/kaisoku.pdf" target="_blank" rel="noreferrer">会則(PDF)</a></div></div></div><div className="copyright">© 2026 つくばフリースクール等連携協議会</div></footer>}
function SchoolCard({school, id}:{school:typeof schools[number]; id?:string}){const [open,setOpen]=useState(false);const href = school.site!=="#" ? school.site : school.insta;return <div id={id} className="school-card-wrap"><a href={href} target="_blank" rel="noreferrer" className={`school-card ${school.tone} school-card-desktop`}><div className="school-body"><div className="card-meta"><span><MapPin size={13}/>{school.area}</span></div><h3>{school.name}</h3><p>{school.comment}</p><div className="school-tags"><span>{school.target}</span><span className="school-go" aria-hidden="true"><ArrowUpRight size={15}/></span></div></div></a><div className={`school-card-mobile${open?" is-open":""}`}><button type="button" className="school-mobile-head" aria-expanded={open} onClick={()=>setOpen(!open)}><span className="school-mobile-area"><MapPin size={12}/>{school.area}</span><span className="school-mobile-name">{school.name}</span><span className="school-mobile-chevron" aria-hidden="true">{open ? "−" : "+"}</span></button>{open && <div className="school-mobile-body"><p>{school.comment}</p><div className="school-tags"><span>{school.target}</span></div><a className="school-site-link" href={href} target="_blank" rel="noreferrer">公式サイトへ →</a></div>}</div></div>}
const sortedSchools=[...schools].sort((a,b)=>a.yomi.localeCompare(b.yomi,"ja"));
export default function Home(){useEffect(() => { document.title = "つくばフリースクール等連携協議会｜学校以外の学びの場・居場所を探している方へ"; }, []); const [areaFilter,setAreaFilter]=useState<"all"|"tsukuba"|"mirai">("all"); const visibleSchools=sortedSchools.filter(s=>areaFilter==="all"||(areaFilter==="mirai"?s.area.startsWith("つくばみらい市"):s.area.startsWith("つくば市"))); const chooseArea=(area:"all"|"tsukuba"|"mirai")=>{setAreaFilter(area); if(area==="mirai") window.setTimeout(()=>document.getElementById("imakoko")?.scrollIntoView({behavior:"smooth",block:"center"}),50)}; return <div className="site-page sky-page"><div className="sky-fixed" aria-hidden="true"/><Header/><main><section className="hero"><div className="hero-copy"><p className="eyebrow">TSUKUBA FREE SCHOOL NETWORK</p><h1>学校以外の<br/><em>学びの場・居場所を</em><br/>探している方へ</h1><p className="hero-lead">つくばフリースクール等連携協議会は、<br/>学校の外にあるまなびの場と、<br/>子どもたち・ご家族をつなぐネットワークです。</p><div className="hero-actions"><a className="button button-primary" href="#schools">参加スクール一覧 <span>↓</span></a></div><p className="last-updated hero-updated">最終更新：2026/10/6　<a href="/history">更新履歴 はこちら →</a></p></div><div className="hero-art"><img className="hero-child" src="/assets/child02-1.png" alt="フリースクールへ向かう子どもたち" /></div></section>

		<section className="letter-section"><div className="section-heading"><div><p className="eyebrow">MONTHLY LETTER</p><h2>つくば不登校・<em>多様な学びの場だより</em></h2></div></div><div className="letter-card"><div className="letter-image-slot letter-image-ready"><ImageViewer src="/assets/tayori-2026-10.png" alt="つくば不登校・多様な学びの場だより 2026年10月号" showShare={false}/></div><div className="letter-copy"><h3>2026年10月号</h3><p className="letter-line">各スクールの空き状況・近況報告</p><p className="letter-note">を毎月更新でお届けしています</p><a className="letter-pickup" href="/letters">バックナンバーはこちら →</a><div className="letter-share"><ShareButtons src="/assets/tayori-2026-10.png" alt="つくば不登校・多様な学びの場だより 2026年10月号"/></div></div><div className="letter-lines"><span></span><span></span><span></span></div></div><div className="pickup-action"><a className="archive-link" href="https://note.com/tfc298/n/n715b43550966" target="_blank" rel="noopener noreferrer">ピックアップ「子ども社会塾」の詳細を見る <span>→</span></a><small>外部サイトが開きます</small></div></section>
		<section className="schools-section" id="schools"><div className="section-heading"><div><p className="eyebrow">SCHOOLS & PLACES</p><h2>参加スクール一覧</h2><p className="section-lead">それぞれの場所に、それぞれの学び方。<br/>気になるところから、公式サイトをのぞいてみてください。</p></div><div className="filter-tags"><button type="button" className={areaFilter==="all"?"active":""} onClick={()=>chooseArea("all")}>すべて</button><button type="button" className={areaFilter==="tsukuba"?"active":""} onClick={()=>chooseArea("tsukuba")}>つくば市</button><button type="button" className={areaFilter==="mirai"?"active":""} onClick={()=>chooseArea("mirai")}>つくばみらい市</button></div></div><div className="schools-grid">{visibleSchools.map(s=><SchoolCard key={s.name} id={s.name.includes("imakoko")?"imakoko":undefined} school={s}/>)}</div><div className="map-note"><ImageViewer src={storageImage} alt="参加団体の位置を示した地図" showShare={false}/><div className="map-note-text"><p className="eyebrow">AT A GLANCE</p><h3>マップから探す</h3><p>パンフレットには、各スクールの所在地と特徴をまとめています。詳細は各公式サイトをご確認ください。</p><ShareButtons src={storageImage} alt="参加団体の位置を示した地図"/></div></div></section><section className="quick"><div className="quick-label">あなたに合わせた<br/><b>入口</b>から</div><a href="/parents"><b>保護者の方へ</b><small>相談したい、話を聞いてほしい</small><strong>→</strong></a><a href="/join"><b>団体の方へ</b><small>スクールを掲載・参加したい</small><strong>→</strong></a><a href="/donation"><b>応援したい方へ</b><small>寄附を受け付けています</small><strong>→</strong></a></section>
</main><Footer/></div>}
